
[orchestrator]
<orch_vm_ip> ansible_ssh_private_key_file=/root/.ssh/id_rsa

# lb host is where the HAProxy will be installed. If Customer is using loadbalancer appliance for kubeAPI and Ingress, then this is not needed.
[lb]
<orch_vm_ip> ansible_ssh_private_key_file=/root/.ssh/id_rsa
    
