apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  namespace: openshift-ingress-operator
  name: default
spec:
  endpointPublishingStrategy:
     type: LoadBalancerService
     loadBalancer:
        scope: Internal
